### ISSUE TITLE
Obsidian Clipper only captures half of the page.

### ISSUE THREAD

**Issue by benpryde** [DominikPieper/obsidian-ReadItLater#100]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

When click on the capture icon in the address bar, I'm expecting the obsidian clipper to capture the entire page of text.

### Current behaviour

When click on the capture icon in the address bar, obsidian clipper captured only half of the entire page of text.

### Steps to reproduce

1. step up obsidian clipper
2. go to this [web page in question](https://www.qcc.cuny.edu/nursing/prospective.html)
3. when you're on the above web page, click on the obsidian clipper within the address bar.
4. check saved page in obsidian
5. obsidian clipper only captured less than half of the web page text (from beginning to right before "Estimated Fees for Nursing Students") 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.2.7

### Plugin Version

1.2.0

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

**Comment by lukacovicadam** [comment]
Apparently this site has strange HTML markup because [Readability](https://github.com/mozilla/readability) is unable to detect article region. I also tried to save this page with MarkDownload browser addon but got the same result.

Site is neither eligible for custom parser because its content is too diverse. I suggest manually copy missing text to your note.

**Comment by benpryde** [comment]
i figured it might be problem with site's code.

I tried 4 read-it-later apps, omnivore, pocket, raindrop, instapaper. While omnivore and pocket doesn't capture the entire content. Raindrop and instapaper did an excellent job on saving all of the texts.

**Comment by lukacovicadam** [comment]
I was curious, so I created account on Raindrop and Instapaper, but, result is far from excellent (my opinion).

On Raindrop you get basically an iframe which means when URL of page is changed without proper redirect or no longer available you lost it. Of course, you can pay for "Pro" and copy of site will be stored for you, but it's still HTML in iframe and not Markdown file.

Instapaper was confused even more than Readability. For some reason it saved home page and not that article. 

![pic-selected-230514-2254-13](https://github.com/DominikPieper/obsidian-ReadItLater/assets/10731521/a22d8711-fedf-40f7-a925-a831eb2156f7)

All in all, this site has really bad HTML.

**Comment by benpryde** [comment]
I'm not a fan of raindrop as well

but my instapaper result differs from yours. It captured the entire page with great readability.

![Screenshot 2023-05-14 at 17-24-49 Queensborough Community College](https://github.com/DominikPieper/obsidian-ReadItLater/assets/65054301/0d4f6304-7264-46ba-ab9f-0fe079ace1df)

i captured it via firefox instapaper plugin, hope this helps.
I really like your plugin, and I want to use it. Unfortunately, i'm the kind of person who doesn't check his article after saving, so i need something that can also deal with bad html also.

it doesn't seems like it, but if you have the smallest possibility of fixing this, please let me know, so i can keep an eye on this plugin! thank you
