### ISSUE TITLE
Cancel auto-play of embedded bilibili videos

### ISSUE THREAD

**Issue by Ce1este** [DominikPieper/obsidian-ReadItLater#102]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Embedded Bilibili videos will play automatically, and videos in reading mode and editing mode will play simultaneously.

### ✔️ Solution

It gets worse when I preview a lot of pages with bilibili embedded videos at the same time.
So I want the embedded bilibili video not to play automatically when I open the page.

### ❓ Alternatives

Add "&autoplay=0" to cancel auto-play
For example:
```html
<iframe width="${this.settings.bilibiliEmbedWidth}" height="${this.settings.bilibiliEmbedHeight}" src="https://player.bilibili.com/player.html?bvid=${n}&autoplay=0" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe>
```

### 📝 Additional Context

I'm not sure if anyone needs the video autoplay feature when opening the page.
Maybe make a button in the settings page to switch this setting on and off?

---

(And Thank you for creating the plugin, it helped me a lot.)

**Comment by lukacovicadam** [comment]
Thanks for the report.

There's no need to create setting for enabling autoplay. As you mentioned, autoplay of embedded content causes only complications.
