### ISSUE TITLE
Add YouTube's Date Published

### ISSUE THREAD

**Issue by CamronWalker** [DominikPieper/obsidian-ReadItLater#104]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I'd like the date a youtube video was published. 

### ✔️ Solution

PR https://github.com/DominikPieper/obsidian-ReadItLater/pull/105
Add the %videoPublishDate% under the youtube template options. Example Below:

![image](https://github.com/DominikPieper/obsidian-ReadItLater/assets/30887472/d4cb6ff4-d9e9-422e-ad7f-afb8503d314b)

**Comment by CamronWalker** [comment]
I created a pull request for this: https://github.com/DominikPieper/obsidian-ReadItLater/pull/105

**Comment by lukacovicadam** [comment]
Released in [0.3.1](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.3.1)
