### ISSUE TITLE
[FR]Support for “x.com"

### ISSUE THREAD

**Issue by kazdonkai** [DominikPieper/obsidian-ReadItLater#114]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests

When I copy a Twitter link on my iPad, it becomes “x.com" and is not recognized as Twitter.
On desktop, it will be “x.com" in the future.
So, please improve it so that “x.com" is recognized as Twitter.

**Comment by adamluckdev** [comment]
Fixed in #118

**Comment by adamluckdev** [comment]
Released in [0.4.0](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.4.0)
