### ISSUE TITLE
Private URLs can't be bookmarked

### ISSUE THREAD

**Issue by fa5trac3r** [DominikPieper/obsidian-ReadItLater#115]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

When I try to add a URL that is not exposed to the public internet or is protected it should just add it like a source link, as it does for unreadable article.

### Current behaviour

currently if i try to save the url to the clipboard it it doesn't do anything

### Steps to reproduce

it can be reproduced by trying to access some protected URL link which isn't available to the public internet.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.3.7

### Plugin Version

0.3.1

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

### Possible solution

the fix can be for the urls which can't be parsed, we can save just the src link as in the document

**Comment by adamluckdev** [comment]
Can you provide example URLs, please?

**Comment by fa5trac3r** [comment]
ex. https://midway-auth.amazon.com/login?next=%2F

**Comment by adamluckdev** [comment]
It throws **net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED** error which is not well documented. I only found this post on [Google Groups](https://groups.google.com/a/chromium.org/g/net-dev/c/C2zAEfT1LWw), but it doesn't bring any suggestions how to fix it, besides editing server configuration which is out of our scope.
