### ISSUE TITLE
Imbedded YouTube links should have an option to enable 'privacy-enhanced mode'

### ISSUE THREAD

**Issue by vfxninjaeditor** [DominikPieper/obsidian-ReadItLater#116]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

YouTube enables you to imbed links with 'privacy-enhanced mode' which essentially only changes the link to a youtube-nocookie link. There should be an option to enable this in the settings, or it should be default.

### ✔️ Solution

![image](https://github.com/DominikPieper/obsidian-ReadItLater/assets/31264172/a97b54fd-7075-43c8-a843-14a6f44f2674)

**Comment by adamluckdev** [comment]
Added in #119

**Comment by adamluckdev** [comment]
Released in [0.4.0](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.4.0)
