### ISSUE TITLE
[FR] If downloading the image fails, keep the image link.

### ISSUE THREAD

**Issue by wwjCMP** [DominikPieper/obsidian-ReadItLater#123]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Some websites have anti-web scraping features for images, which cause automatic image downloads to fail. When images fail to download, it is hoped that the network connection to the images can be preserved. The current situation is that the image links disappear.

### ✔️ Solution

Check if the image has been downloaded successfully, if not, retain the network connection to the image.

**Comment by adamluckdev** [comment]
Can you provide example  URL so I can test it and eventually implement it?
