### ISSUE TITLE
%date% variable not filled in stackoverflow answer template

### ISSUE THREAD

**Issue by mayukhc** [DominikPieper/obsidian-ReadItLater#124]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

%date% variable should be filled in for stackoverflow answer template. 

### Current behaviour

%date% variable not being filled in for stackoverflow answer template. Added screenshots of my templates and saved file from [this stackexchange question](https://quant.stackexchange.com/questions/3009/how-to-fit-probability-density-function-from-sample-moments) . 

#### Template

![Templates](https://github.com/DominikPieper/obsidian-ReadItLater/assets/8831148/b41facca-dc0f-4fee-8e43-94dcb77d1a14)

#### Saved Page - %date% not filled in the answers

![ReadItLaterSave](https://github.com/DominikPieper/obsidian-ReadItLater/assets/8831148/e45d26f2-5cbc-4516-ba6b-2597c245e0b7)

I thought templater/natural language dates plugin might be causing it, so also tested with other plugins disabled. It's working in title and question note template, only answer note template's not being filled. 

### Steps to reproduce

Include %date% in stackexchange answer template, and save any stackexchange.com page. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version

1.4.14

### Plugin Version

0.3.1

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

**Comment by adamluckdev** [comment]
Fixed in #128

**Comment by adamluckdev** [comment]
Released in [0.4.0](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.4.0)
