### ISSUE TITLE
Error net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED while saving some articles

### ISSUE THREAD

**Issue by indicatorvariable** [DominikPieper/obsidian-ReadItLater#125]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

The articles should be saved

### Current behaviour

The article is not saved and throws the following error in console:
Uncaught (in promise) Error: net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)

### Steps to reproduce

1. Copy this URL : https://www.thehindu.com/sci-tech/science/attophysics-new-tools-to-fathom-the-world-of-electrons-explained/article67393728.ece

2. From command palette, choose read-it-later save this article

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.4.14

### Plugin Version

0.3.1

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

**Comment by adamluckdev** [comment]
Unfortunately, as I wrote in #115 , this error is not well documented and I'm unable to debug it properly since it happens in Electron layer of Obsidian. I'll create issue in Obsidian project and hopefully someone will help me resolve it.

The good news is that mobile app is currently not affected and article was successfully saved.

**Comment by adamluckdev** [comment]
Unfortunately, even Obsidian developer [wasn't able to resolve this issue](https://github.com/obsidianmd/obsidian-api/issues/137). Let's hope update of Electron in the future will fix it.

**Comment by mayukhc** [comment]
The url is being saved correctly on on my system (Linux, Obsidian 1.4.16,plugin 0.4), so could be a config issue on some systems.
