### ISSUE TITLE
add Variables with spaces replaced with underbars

### ISSUE THREAD

**Issue by raynear** [DominikPieper/obsidian-ReadItLater#137]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I want to add variable as tags. but channelName has space. so that cannot be tag.

### ✔️ Solution

add spacebar removed variable

**Comment by adamluckdev** [comment]
You can use new template engine with `replace` filter.

`{{ videoTags|replace(' ', '_') }}`
