### ISSUE TITLE
Android companion App

### ISSUE THREAD

**Issue by Undertone5936** [DominikPieper/obsidian-ReadItLater#140]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Reat it later is great! Thanks.

I am not able to leverage all its power, though, because I use Obsidian only on PC and do all my capturing on my android phone.

Therefore, I rarely am able to use this wonderful plug in, since I dont have Obsidian around when I encounter something worth saving to Read it later.

### ✔️ Solution

In my use case, it would be great to have a companion android app with a quick add button on the home screen.

Every time I select the quick add button on the home screen, the clipboard contents would be copied to "Read it later companion app".

Then, on the background, or upon user request, the app would sync with Obsidian on my PC.

**Comment by e-p-s** [comment]
+1

**Comment by DominikPieper** [comment]
I can't test it cause I don't own a Android phone

**Comment by Medullitus** [comment]
you can always use android studio to develop apps for android
