### ISSUE TITLE
Fix YouTube thumbnails

### ISSUE THREAD

**Issue by Nitero** [DominikPieper/obsidian-ReadItLater#143]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

Youtube thumbnails should look nice out of the box

### Current behaviour

The plugin gives links to the thumbnails in the 4:3 format which have black borders at the top and bottom

### Steps to reproduce

Save a youtube video and show the provided image link in the file with something like `![thumbnail|300](https://i.ytimg.com/vi/IuH19h0UKIo/default.jpg)`

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.5.8

### Plugin Version

0.4.0

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs

### Possible solution

The provided link could be adjusted from `.../default.jpg` to `.../mqdefault.jpg` as per [this](https://stackoverflow.com/questions/13220715/removing-black-borders-43-on-youtube-thumbnails)

**Comment by adamluckdev** [comment]
Fixed in #151
