### ISSUE TITLE
Long file names for saved images

### ISSUE THREAD

**Issue by mariavd** [DominikPieper/obsidian-ReadItLater#145]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I have enabled downloading the images included in an article to their own directory and that works but the problem is that the file names of the images contain the URL and they tend to become very long. I back up my vault using git and often it refuses to commit the files because of the long path. Then I have to manually go and rename the pictures, so that I can make a commit again. 

### ✔️ Solution

Exclude the URL from the file name

### 📝 Additional Context

![image](https://github.com/DominikPieper/obsidian-ReadItLater/assets/24567145/86188ca3-b39c-419e-bc5f-594d005095db)

**Comment by adamluckdev** [comment]
Upgrade to the latest version, please. It contains refactored image downloading process.
