### ISSUE TITLE
Remove illegal chars from properties

### ISSUE THREAD

**Issue by Nitero** [DominikPieper/obsidian-ReadItLater#153]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

Inserting a youtube title as string into a property should work

### Current behaviour

When saving a youtube video where the title includes illegal characters like `"` and writing this title to a property like below will result in a YAML error which breaks the properties. This can be prevented by not putting the title in quotes, but I think this is suboptimal because then it is is not clear that this property should be treated as a string.

![image](https://github.com/DominikPieper/obsidian-ReadItLater/assets/11302557/9c3bb16a-4fb7-4f28-a97b-8db140df4ada)

### Steps to reproduce

Have this as your youtube template and try to save [this video](https://www.youtube.com/watch?v=OzKA0UzSo6I).
```
---
titleAsString: "%videoTitle%"
titleNoString: %videoTitle%
---
```

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.6.3

### Plugin Version

0.4.0

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs

### Possible solution

It seems to work for the file name so maybe just reuse that logic for all properties? Or are there different illegal characters for YAML than for the file name?

**Comment by adamluckdev** [comment]
Please update to the newest version with the new template engine. Then you can use this syntax to replace quotes in the Youtube video title.

```
---
titleAsString: "{{ videoTitle|replace('"') }}"
---
```

**Comment by Medullitus** [comment]
> Please update to the newest version with the new template engine. Then you can use this syntax to replace quotes in the Youtube video title.
> 
> ```
> ---
> titleAsString: "{{ videoTitle|replace('"') }}"
> ---
> ```

Hello. Thank you for your response. Could you explain how we can apply the template you shared?
