### ISSUE TITLE
Headings in Substack posts are not parsed

### ISSUE THREAD

**Issue by minhdqdev** [DominikPieper/obsidian-ReadItLater#154]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

All headings in a Substack post should be parsed correctly to markdown headings.

### Current behaviour

Every heading in a Substack post is stripped out in the markdown note.

### Steps to reproduce

1. Copy a URL of a Substack post to clipboard, for example: https://newsletter.systemdesign.one/p/redis-use-cases
2. Run the command "ReadItLater: Save clipboard"  in Obsidian.

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.6.7

### Plugin Version

0.4.0

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

### Possible solution

I have investigated this issue and found a solution implemented by the [markdownload](https://github.com/deathau/markdownload) browser extension. Put like this:

```javascript
document.body.querySelectorAll('h1, h2, h3, h4, h5, h6')?.forEach(header => {
    // Readability.js will strip out headings from the dom if certain words appear in their className
    // See: https://github.com/mozilla/readability/issues/807  
    header.className = '';
    header.outerHTML = header.outerHTML;  
...
const readableDocument = new Readability(document).parse();
});
```

The fastest solution is to modify the WebsiteParser. However, I think Readability trips out those headings for a good reason. A better solution I think is to create a new SubstackParser to solve this issue for the Substack website only.

I can make a pull request to fix this issue. But firstly, I would like to hear your opinion on the best solution to resolve this issue. Thank you.

**Comment by adamluckdev** [comment]
Thanks for the report. I applied some DOM optimizations from markdownload in #158. Dedicated Substack parser is not necessary right now.

**Comment by minhdqdev** [comment]
Great to hear that. I'm gonna close this issue.
