### ISSUE TITLE
I get an error when trying to save something on YouTube

### ISSUE THREAD

**Issue by Medullitus** [DominikPieper/obsidian-ReadItLater#166]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

Being able to save content from YouTube without issues.

### Current behaviour

"Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
    at ti.parseSchema (plugin:obsidian-read-it-later:59:20327)
    at async ti.prepareNote (plugin:obsidian-read-it-later:59:17367)
    at async Rt.processClipboard (plugin:obsidian-read-it-later:146:2921)
    at async Object.callback (plugin:obsidian-read-it-later:146:2433)
    at async te.handleCommand (plugin:obsidian-advanced-uri:10:593)
index.html:1"

"[Deprecation] Custom state pseudo classes are changing from ":--webkit-scrollbar" to ":state(webkit-scrollbar)" soon. See more here: https://github.com/w3c/csswg-drafts/issues/4805"

### Steps to reproduce

Thx

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.6.7

### Plugin Version

0.5.0

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs

**Comment by adamluckdev** [comment]
Can you provide an URL of video you tried to save?

**Comment by Medullitus** [comment]
All YouTube videos. For example: https://www.youtube.com/watch?v=PIT_LlERqe8

I also use Obsidian Web Clipper firefox plugin for your plugin. If the issue is related to that plugin, I can post about it.

**Comment by adamluckdev** [comment]
Thanks for the report, issue was fixed #167.
