### ISSUE TITLE
Error on Youtube clipping similar to #166 that is listed as fixed. Uncaught TypeError: Cannot read properties of null (reading 'frontmatter')

### ISSUE THREAD

**Issue by gothic03** [DominikPieper/obsidian-ReadItLater#168]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

I have been using this fantastic plugin for several months now without getting any errors, and this is how I would like for it to continue to operate.

### Current behaviour

I am getting a notification that the note was created successfully as it was before, and this is true.  Note is being created and it seems to be normal.  However, I am getting several message boxes popping up with eh above error messages as noted int he subject line.  I have included a screen capture for your reference.  Plugin seems to be functioning fine even with the errors, but something is not right.  More of a nuisance than anything, but may be an indicator of larger issue somewhere else??

![image](https://github.com/user-attachments/assets/d6ca3b4e-0d1c-48dc-aae1-00133135716e)

### Steps to reproduce

Just activate command ReadItLater: Save Clipboard via a hotkey for any YouTube video.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.6.7

### Plugin Version

0.5.1

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs

### Possible solution

Thought maybe it was having an issue with a property that I am adding via the template, but it a blank value. (I add it manually later).  Removed it from the template, and issue still persists.

**Comment by adamluckdev** [comment]
I was unable to replicate this issue, even with the same video.

Please provide your YouTube template, so I can investigate more. Also, did you try disabling other plugins?

**Comment by gothic03** [comment]
Hmm. Interesting. I have not. I will give that a try. The template has been
fine and untouched for some time other than me removing the one blank
property I mentioned. I will try disabling other plug-ins and see if I can
find it. I have several that recently updated.

Thanks for the quick response.
