### ISSUE TITLE
Doesn't work on Linux with Advanced URIs

### ISSUE THREAD

**Issue by Asten-Valentinus** [DominikPieper/obsidian-ReadItLater#173]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

ReadItLater saves the site that Advanced URIs instructs it to.

### Current behaviour

On the surface, it seems to do nothing but focus/open Obsidian, but looking in the console you can see that ReadItLater throws an error:
```
app.js:1 Obsidian Developer Console
node:electron/js2c/renderer_init:2 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
warnAboutInsecureCSP @ node:electron/js2c/renderer_init:2
app.js:1 Received URL action Object
app.js:1 Uncaught (in promise) Error: Request failed, status 403
    at new t (app.js:1:2030716)
    at vK (app.js:1:2030908)
    at app.js:1:2031587
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
app.js:1 Received URL action Objectaction: "adv-uri"filepath: "Home Index/today.md"[[Prototype]]: Object
app.js:1 Received URL action Objectaction: "advanced-uri"commandname: "ReadItLater: Save clipboard"vault: "Obsidian Vault"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
plugin:obsidian-read-it-later:146 Uncaught (in promise) DOMException: Failed to execute 'readText' on 'Clipboard': Document is not focused.
    at Rt.processClipboard (plugin:obsidian-read-it-later:146:2908)
    at Object.callback (plugin:obsidian-read-it-later:146:2444)
    at te.handleCommand (plugin:obsidian-advanced-uri:10:604)
    at ge.chooseHandler (plugin:obsidian-advanced-uri:14:6726)
    at ge.onUriCall (plugin:obsidian-advanced-uri:14:6436)
    at eval (plugin:obsidian-advanced-uri:14:4534)
    at t (app://obsidian.md/app.js:1:2281449)
    at <anonymous>:1:52
    at node:electron/js2c/renderer_init:2:16470
    at IpcRendererInternal.<anonymous> (node:electron/js2c/renderer_init:2:10723)
```

### Steps to reproduce

1. Install both Advanced URI and ReadItLater Obsidian plugins on a Linux system.
2. Install Obsidian Clipper into browser (I use a fork of Firefox)
3. Open a web page in the browser
4. Press the Clip page button. In Firefox, this is found at the right of the URL bar.
5. Observe Obsidian not saving the page. Look at the console log.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version

1.6.7

### Plugin Version

ReadItLater 0.5.1 with Advanced URI 1.44.1 and Obsidian Clipper 2.0.0

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

### Possible solution

I have no idea what could be causing this, as I have very little experience with development in general, and no experience with JavaScript.

Obsidian Clipper is not the problem; the URI is fine, and the URL is saved to the clipboard. The problem occurs when you open the URI manually in the browser as well.

This may be a problem with ReadItLater, Advanced URI, or both.

See the parallel issues on Advanced URI and Obsidian Clipper:
[Issue 188 on Advanced URI](https://github.com/Vinzent03/obsidian-advanced-uri/issues/188)
[Issue 11 on Obsidian Web Clipper](https://github.com/ClarkAllen1556/obsidian_clip/issues/11)

**Comment by adamluckdev** [comment]
Although extension is not affiliated with plugin I gave it try (Linux with Wayland session), but everything works. I tried multiple scenarios, but none of them gave me yours or other exception.
