### ISSUE TITLE
Expose processContent() function to Plugins 

### ISSUE THREAD

**Issue by jasondavis** [DominikPieper/obsidian-ReadItLater#178]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I would like to use the ReadItLater plugin to generate notes from other plugins and user scripts from plugins like:
- QuickAdd
- Templater
- Modal Forms
- Etc…

if we could expose the processContent() function or create a similar function in ReadItLater that is exposed through the plugin API so other plugins and scripts could execute it and get the generated text returned to the script that is calling the function.  This would make this plugin even more extendable and useful.

### ✔️ Solution

….

### ❓ Alternatives

I was going to fork this plugin and add my own features but thought I would put the idea here first as I would like to see it in this plugin instead

### 📝 Additional Context

Thanks for this plugin It works good and has a nice structure to add other sites

**Comment by joeyfigaro** [comment]
Seconding this request!
