### ISSUE TITLE
Twitter threads

### ISSUE THREAD

**Issue by ashishbhateja** [DominikPieper/obsidian-ReadItLater#19]
Is there a way to save twitter threads?

**Comment by DominikPieper** [comment]
Right now there's no such feature

**Comment by mvrai** [comment]
Having this feature would be great! 
There is a  plugin that can handle it, but it does require a twitter bearer token: 
https://github.com/kbravh/obsidian-tweet-to-markdown

Could @DominikPieper kindly take a moment to look into this and share his input?

**Comment by lukacovicadam** [comment]
Closing as duplicate of #91
