### ISSUE TITLE
Feature Request: Customizable fonts for reading

### ISSUE THREAD

**Issue by cashew90** [DominikPieper/obsidian-ReadItLater#2]
Thank you for the plug-in. It'd be great if one could change the font for preview mode. I like to use a mono-spaced font for notes and it would be great if I could differentiate read-it-later-notes/texts visually from the rest of my notes. It's really more a look-and-feely thing but I would greatly appreciate it as it would help me to get into "reading mode". Just like the Longform plugin solves this.

**Comment by DominikPieper** [comment]
I'm not sure the plugin is the correct place to do this. Rn the only thing it does is to load the content of the links into markdown files. Everything more is handled by Obsidian

**Comment by lukacovicadam** [comment]
As @DominikPieper suggested, it's out of the plugin's scope.

You can customize fonts with CSS snippets - tutorial is [here](https://forum.obsidian.md/t/how-to-change-font/10927)
