### ISSUE TITLE
saving tiktok url

### ISSUE THREAD

**Issue by derpieler** [DominikPieper/obsidian-ReadItLater#25]
so far i have been able to back up tiktok video links. Since yesterday only the name of the content creator, url appears and the note: Sign up to follow creators, give videos likes and view comments.
Where can I enter my credentials for tiktok so that link generation works again.

Thanks for your help

**Comment by DominikPieper** [comment]
Hey, I’m sure I’m not totally sure why it worked at all. I don’t have any add specific TikTok support. I don’t even use it myself 😅

**Comment by derpieler** [comment]
isn't it the same problem everywhere you log in?
Have already logged in on all browsers and already changed a template to:
[[ReadItLater]] [[Article]]

# [%articleTitle%](<iframe 
src="%articleURL%) scrolling="no" 
style="height: 600px; border: 0px none; width: 550px; margin-top: -55px; margin-left: 5px; 
margin-right: 0px; ">
</iframe>

%articleContent%
I thought I could force the login that way.
Everywhere I am logged in, but the message remains the same.
Do you have an idea?

**Comment by DominikPieper** [comment]
Unfortunately not really. I'm not sure yet how to solve that problem for pages like this.

**Comment by lukacovicadam** [comment]
Implemented in #94

**Comment by lukacovicadam** [comment]
Released in [0.3.0](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.3.0)

**Comment by ameyxd** [comment]
@adamluckdev - mentioned elsewhere but tiktok links don't seem to be working with iOS. Any thoughts? I could help!

**Comment by adamluckdev** [comment]
@ameyxd Create new issue, please. Thanks
