### ISSUE TITLE
Feature request: create iOS shortcut to save webpages from share sheet

### ISSUE THREAD

**Issue by xinyirenxinyi** [DominikPieper/obsidian-ReadItLater#27]
Hi and first of all thank you for the plugin! It's such an elegant solution for saving content into obsidian.

I had the idea of using this plugin to solve Obsidian's longstanding problem (as far as I know) of not having an iOS share sheet option, see for instance https://forum.obsidian.md/t/feature-ios-share-sheet-extension/14873/43. A possible apple Shortcut workflow could go: copy current webpage url > open obsidian > trigger the plugin with the copied link.

Just an idea! Kudos again to the plugin.

**Comment by adamluckdev** [comment]
Hi, you can enable this feature since [0.3.0 release](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.3.0).
