### ISSUE TITLE
Unable to load plugin after update

### ISSUE THREAD

**Issue by Hansilein00726** [DominikPieper/obsidian-ReadItLater#29]
After the update a few minutes ago , I suddenly get a message: "Unable to load plugin." Reloading the app and the like didn't work. Before everything worked just fine. I am on Samsung S4 Tablet with Android. 

Please repair!;-) Like the app really. In case you need more info, please refer back to me.

**Comment by DominikPieper** [comment]
I just saw this a few minutes ago on my phone😅 seems like one of the new dependencies didn’t work anymore. I’ll fix as soon as possible

**Comment by Hansilein00726** [comment]
Great to hear! Obsidian seems to have changed a lot with the new version. But Read it Later Plugin worked really great before. I would miss it a lot.

**Comment by DominikPieper** [comment]
It definitely wasn’t planned to break compatibility 😅

**Comment by Hansilein00726** [comment]
Didn"t break compatibility, just deleted the internet.😆

**Comment by suny24x7** [comment]
> After the update a few minutes ago , I suddenly get a message: "Unable to load plugin." Reloading the app and the like didn't work. Before everything worked just fine. 

I'm also facing this problem. So dependent on this plugin.

**Comment by DominikPieper** [comment]
Fixed with the latest version :-)

**Comment by Hansilein00726** [comment]
Hi Dominik,
the man with the bad jokes is bad. Just wanted to inform you that after the update of today everything seems to work as nice and neat as before. Just did the first try. I will continue to test your plugin in the near future, since I collected quiet a few links that I want to convert now. Thank you for repairing this handy little peace of software.

Do I have to close this issue? I am still not familiar with Github customs.

**Comment by DominikPieper** [comment]
Nice t hear. I'll close this now you don't need to do anything :-)
