### ISSUE TITLE
Error capturing some links

### ISSUE THREAD

**Issue by javiavid** [DominikPieper/obsidian-ReadItLater#3]
It's strange, but some work and others do not.
In both links the plugin indicates that it has been created satisfactorily, but in the first one Note MD is created correctly and in the second no.

YES
https://www.youtube.com/watch?v=4WtpTra0SKo

NO
https://www.youtube.com/watch?v=JLk5jIHpvxE

**Comment by DominikPieper** [comment]
Thanks for the issue, I’ll search for a solution

**Comment by javiavid** [comment]
Another example
https://github.com/914191848/Migrate-Notion-to-Obsidian

**Comment by alpererm** [comment]
What I noticed is that if a link contains characters, which are not allowed in a file name this problem occurs.
![image](https://user-images.githubusercontent.com/19191031/136698038-bd70fa52-8351-4d83-92ea-a5ba44b7f5e2.png)

**Comment by DominikPieper** [comment]
Hey, should work now. I missed some of the illegal characters for file names

**Comment by javiavid** [comment]
Hi Dominik, 
I found another website that doesn't work.
https://www.xataka.com/otros/pelea-carne-alternativa-tambien-se-juega-espana-estas-startups-empresas-que-disenan-producen
I can copy it another way, but I'll let you know so you can improve the plugin.
Thank you for your work
