### ISSUE TITLE
Feature Request: Add Tags while clicking ReadItLater

### ISSUE THREAD

**Issue by tinyblckc0000al** [DominikPieper/obsidian-ReadItLater#30]
This plugin is helpful to me : ). And when the information accumulated, I wish I could read or clean some articles of one subject first, which need a classify work done before. So is it possible to add tags when pushing links to Inbox without manually editing note?

**Comment by DominikPieper** [comment]
Hey, the question here is on which base they should be generated? You can create tags with the templates by type but I’m not sure how they should be generated by topic

**Comment by lukacovicadam** [comment]
I can't think of any sensible solution. Even if we'll add custom modal or support for selection of templates you'd have to provide some kind of input. The result will be unnecessary complexity for current workflow.
