### ISSUE TITLE
Feature Request - Additional Youtube Content

### ISSUE THREAD

**Issue by ashtom50** [DominikPieper/obsidian-ReadItLater#32]
Hey. Sorry I put this in Discussions beforre seeing the other feature requests in here.

Really loving this plugin.
It would be really good if the youtube template could also clip the youtube channel name and make it a tag.
This would allow me to have my template looking something like this,

[[ReadItLater]] [[Youtube]]
[%videoTitle%]
Channel: [%YoutubeChannel%]
(%videoURL%)
%videoPlayer%
Notes:

So I could simply click read it later, fill in my notes on the video and its done.

**Comment by anoriginalmoniker** [comment]
+1 This would be really great.

**Comment by apogorzelska** [comment]
+1, being able to get the channel name and ID would be amazing

**Comment by lukacovicadam** [comment]
Released in [0.0.19](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.0.19)
