### ISSUE TITLE
Error importing images

### ISSUE THREAD

**Issue by mbac** [DominikPieper/obsidian-ReadItLater#35]
Hi,

I'm trying to capture [this page](https://www.r-bloggers.com/2022/03/how-to-use-fonts-and-icons-in-ggplot/) into Obsidian, using plugin v. 0.0.14.

I'm getting the following instead of embedded images:

```
![Screenshot from fonts.google.com](Websites/assets/Screenshot%20from%20fonts.google.com..png?w=450&is-pending-load=1#038;ssl=1)![Screenshot from fonts.google.com](Websites/assets/Screenshot%20from%20fonts.google.com..png?w=450&ssl=1)

Figure 1: Screenshot from fonts.google.com
```

The actual URI for the image was:
`https://i1.wp.com/albert-rapp.de/post/2022-03-04-fonts-and-icons/google-fonts.png?zoom=2&w=450&ssl=1`

Screenshot for clarity:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/308068/161442177-ba561543-1084-4a4b-bc7b-1da7c4698007.png">

I've tried the [Pluck](https://github.com/kevboh/obsidian-pluck) plugin for Obsidian; images work fine with it, although its parser mangles the page layout pretty bad.

**Comment by lukacovicadam** [comment]
I'm sorry but images are no longer available thus I cannot replicate issue.
