### ISSUE TITLE
Silent failure with website titles containing slashes

### ISSUE THREAD

**Issue by bjschafer** [DominikPieper/obsidian-ReadItLater#36]
I think this is the same root cause as #34.

If I try to import https://github.com/sorin-ionescu/prezto/tree/master/modules, for example (page title is `prezto/modules at master · sorin-ionescu/prezto`), nothing happens. If I take a peek in the dev console, I see:

```
Uncaught (in promise) Error: ENOENT: no such file or directory, open '/obfuscated/path/Read Later/preztomodules at master · sorin-ionescu/prezto.md'
Promise.then (async)
step @ VM221:30
eval @ VM221:31
__awaiter @ VM221:27
callback @ VM221:6353
vz @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
```

I'm not real familiar with the code (or TS in general), but it looks like the function at https://github.com/DominikPieper/obsidian-ReadItLater/blob/master/src/helpers/fileutils.ts#L30 should have solved this problem already.

Let me know if I can provide further info.

**Comment by lukacovicadam** [comment]
Fixed in 0.0.16
