### ISSUE TITLE
Feature Request - Add Date Variable to Titles

### ISSUE THREAD

**Issue by anoriginalmoniker** [DominikPieper/obsidian-ReadItLater#37]
It would be great if I could add a date variable in a customizable format to the titles of imports. I tend to prepend all my sources with the date I imported them.

**Comment by czhad** [comment]
It would be great to add the %date% variable to all the import types. I'd like to have a template like the example below everywhere, and it doesn't work now. I don't really get the reasoning behind having different variable sets available for differenty import types, wouldn't it be much easier to have it unified?

Template example:
---
date: %date%
tags:
  - ReadItLater/Article
---

# [%articleTitle%](%articleURL%)

%articleContent%

**Comment by lukacovicadam** [comment]
Added in 0.0.15
