### ISSUE TITLE
URL isn't being inserted properly into the heading

### ISSUE THREAD

**Issue by dpendolino** [DominikPieper/obsidian-ReadItLater#49]
Example parsing from https://dns.coffee:

```
[[ReadItLater]] [[Article]]

# home - DNS Coffee

DNS Coffee?

DNS Coffee collects and archives stats from DNS [Zone files](https://en.wikipedia.org/wiki/Zone_file) in order to provide insights into the growth and changes in DNS over time.
```

When I modify the template to use the article url in the body:

```
[[ReadItLater]] [[Article]]

# [%articleTitle%](%articleURL%)

%articleContent%

# [%articleTitle%](%articleURL%)
```

It will then parse correctly:

```
[[ReadItLater]] [[Article]]

# home - DNS Coffee

DNS Coffee?

DNS Coffee collects and archives stats from DNS [Zone files](https://en.wikipedia.org/wiki/Zone_file) in order to provide insights into the growth and changes in DNS over time.

# [home - DNS Coffee](https://dns.coffee/)

```

Obsidian Version:
![image](https://user-images.githubusercontent.com/1458421/184517670-abd87c02-af97-4319-9e1c-b6ed0aa5a3d5.png)
OS: Arch Linux
Plugin Version: The latest from the community and also latest commit from `main` on GitHub

**Comment by lukacovicadam** [comment]
Unfortunately, I'm not able to replicate it either with default or your article template. Maybe some other plugin is causing this. Please check if any of your installed plugins manipulate with headings in notes.

**Comment by dpendolino** [comment]
Yup that was it! The conflict was with https://github.com/dvcrn/obsidian-filename-heading-sync and the solution if anyone needs it is to add an ignore rule for the ReadItLater folder.

Thanks!
