### ISSUE TITLE
Feature Request: Subdirectories for each article including assets

### ISSUE THREAD

**Issue by tadly** [DominikPieper/obsidian-ReadItLater#50]
I'd love to have subdirectories for all downloaded articles as this would make deleting them much easier.
Currently I can't simply delete the assets directory as it will contain assets for other articles as well.

Assuming we have 3 Articels saved for reading later like this...
![image](https://user-images.githubusercontent.com/503647/188087650-f315d465-eb36-4b04-9219-218eda27ede9.png)

...and I want to delete the current one - _Which color is best in a living room?_ - I now have to manually filter through the **assets** directory and figure out what images belong to this artikel.

Instead I'd propose to create subdirectories like this:
![image](https://user-images.githubusercontent.com/503647/188088528-7ce94c37-6635-4a76-8461-b96767e5e4c4.png)
Now I can simply delete the folder and be done with it.

This could/should probably be an option for the user to configure.

**Comment by lukacovicadam** [comment]
Added in 0.0.17
