### ISSUE TITLE
Feature Request: Mobile friendly automation

### ISSUE THREAD

**Issue by tadly** [DominikPieper/obsidian-ReadItLater#51]
I'd like to use obsidian in conjunction with this plugin as kind of a pocket alternative.

As I'm mostly on mobile, using Pocket is much more convenient as I simply share a articel with the app and the rest happens automatically.
With obsidian there are many more steps involved.

I'm not sure of the capabilites for plugins but here's a suggestions how the process could be automated some.

Have a file that's monitored by _ReadItLater_ and when a url is added run the same routine as when executing the "Save clipboard" command.
Afterwards remove the url from the file or flag/tag it as being processed so it doesn't get processed again.

**Comment by lukacovicadam** [comment]
If you're using device with iOS or iPadOS you can use Shortcut for this workflow. Guide is in #24 .

Ideal solution would be add new item to Obsidian share menu. Unfortunately, Obsidian doesn't provide API for this. I'll open issue regarding this.

**Comment by tadly** [comment]
Interesting. I am on android though so I'm out of luck.

If you open an issue with Obsidian, would you mind linking it here so we can follow along?

**Comment by lukacovicadam** [comment]
Here it is.
https://github.com/obsidianmd/obsidian-api/issues/79

**Comment by ramarivera** [comment]
Seeing as how there seems to be a way (or at least that's what the obsidian team message leads me to believe), would there be any chance to add this feature?

**Comment by lukacovicadam** [comment]
Released in [0.3.0](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.3.0)
