### ISSUE TITLE
Option to wrap %articleContent% in blockquotes? 

### ISSUE THREAD

**Issue by iroQuai** [DominikPieper/obsidian-ReadItLater#52]
Hi! 
First of all: great plugin! Very helpful to extract pages for later reading and highlighting. I love the template feature which make using this with my own system a breeze.

Although I do like that the whole content is clipped, I'd like to hide it at first. Preferably by using callouts and collapse them dy default. I couldn't get this to work because article content could have more alineas and only the first alinea would have the > in front.

Is there a way to change this so I can use callouts with the article content?

**Comment by iroQuai** [comment]
This is something I tried within a template:
```
> [!quote] article content
> %articleContent
```
This only works when the content contains one alinea.

**Comment by adamluckdev** [comment]
Update to the newest version with the new template engine and use this syntax to get article content in blockquote.

`{{ articleContent|blockquote }}`
