### ISSUE TITLE
Unable to save "non-parsable" webpages.

### ISSUE THREAD

**Issue by ClarkAllen1556** [DominikPieper/obsidian-ReadItLater#60]
When saving a page that is considered non-parsable, a "File not found" error is thrown:

> `plugin:dev-obsidian-read-it-later:29 Uncaught (in promise) Error: ENOENT: no such file or directory`

**Comment by lukacovicadam** [comment]
Fixed in [0.0.18](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.0.18)
