### ISSUE TITLE
Add in setting to allow adjusting embedded video size

### ISSUE THREAD

**Issue by gwillcox-r7** [DominikPieper/obsidian-ReadItLater#82]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Currently the size of video embeds cannot be changed. There should be an option to change the video embed size vs setting it statically.

### ✔️ Solution

Add in a settings option that allows one to change the default size for video embeds. This can make taking notes easier if you need to work on bigger screens or smaller screens where the default video embed size doesn't work as well for your needs, or if the text in the video is very small.

### ❓ Alternatives

Manually editing the HTML to change the embed size.

**Comment by lukacovicadam** [comment]
Thanks for suggestion. Feature was implemented in #97 and will be included in next release.

**Comment by lukacovicadam** [comment]
Released in [0.3.0](https://github.com/DominikPieper/obsidian-ReadItLater/releases/tag/0.3.0)
