### ISSUE TITLE
Lost images

### ISSUE THREAD

**Issue by kamasylvia** [DominikPieper/obsidian-ReadItLater#86]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

The URL of the article is https://mp.weixin.qq.com/s/SSX2sEcKCzPMPEDDlV5m7Q. It's written in Chinese. Pocket, MarkDownload, and many other apps are able to successfully capture the content of the website.

This screenshot display the result of MarkDownload:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/9450184/226493043-c00fe067-8c90-44f0-ae39-66bc2e1ce841.png">

### Current behaviour

On the other hand, ReadItLater cannot capture images from the article URL.

The screenshot of the result of ReadItLater:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/9450184/226493335-3e73c398-517d-46cf-ac16-a045be44c6b1.png">

### Steps to reproduce

1. Please click on the URL https://mp.weixin.qq.com/s/SSX2sEcKCzPMPEDDlV5m7Q to access the original article.
2. Using Pocket or MarkDownload to save the article can lead to a successful outcome.
3. Capture the article via ReadItLater, the images are not captured on my devices. 

### Which Operating Systems are you using?

- [ ] Android
- [X] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version

1.1.16

### Plugin Version

0.2.0

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

**Comment by bmarsaud** [comment]
I encountered the same issue, this is because images of this article don't have an extension in their file name. ReadItLater tries to get the extension from the image filename to build its local filename.

A better solution would be to use the `Content-Type` header in  the HTTP Response and retrieve the extension from it.
