### ISSUE TITLE
Plugin settings are not being synced across devices

### ISSUE THREAD

**Issue by vadimmelnicuk** [DominikPieper/obsidian-ReadItLater#87]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20bug) didn't find any similar reports.

### Expected Behavior

Plugin settings are synched across all devices

### Current behaviour

Plugin settings are changed on a desktop machine, but are not synced to mobile device. Mobile device still contain default plugin settings.

### Steps to reproduce

1. Install plugin on 2 device i.e., PC and mobile phone.
2. Change plugin settings on a PC and wait for those to be uploaded to cloud.
3. Load Obsidian on mobile and confirm new settings are applied.

### Which Operating Systems are you using?

- [ ] Android
- [X] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.1.16

### Plugin Version

0.2.0

### Checks

- [X] I have tried it with all other plugins disabled and the error still occurs

### Possible solution

It seems like two sets of settings are being created in the plugin folder i.e., data.json (PC) and data(1).json (mobile).
I have found a workaround where I copy/paste settings from data.json to data(1).json manually.
However, it would be great if a single data.json is used across all devices.

_No response_

**Comment by lukacovicadam** [comment]
Unfortunately, I'm not using Obsidian Sync so I'm not able to properly test this issue. However, we're using default way to load settings, just like in [Obsidian Sample Plugin](https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/main.ts#L85).

According to Obsidian Forum, it's frequent question / issue users have. Did you try some of these advice?

[Obsidian Sync not syncing plugins and settings](https://forum.obsidian.md/t/obsidian-sync-not-syncing-plugins-and-settings/37495/1)

**Comment by vadimmelnicuk** [comment]
@lukacovicadam Hey, just to clarify, I am not using Obsidian Sync either. Everything is getting synched using Apple iCloud on my end.

**Comment by lukacovicadam** [comment]
Well, this looks like rather issue with iCloud than plugin. As I mentioned above, we're using default way of loading / saving plugin settings.

Try to do following steps:

- Backup data.json
- Delete data.json from iCloud
- Make sure data.json is removed through Files app on iOS and Finder on macOS
- Create data.json with backup content on one of the device and wait for synchronization

Yes, it's very basic advice but I can't think of any other solution.
