### ISSUE TITLE
Extract multiple links from the clipboard

### ISSUE THREAD

**Issue by lbgws2** [DominikPieper/obsidian-ReadItLater#90]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/DominikPieper/obsidian-ReadItLater/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/DominikPieper/obsidian-ReadItLater/labels/type%3A%20enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Converting URLs from the clipboard to MD files is a great idea. My requirement is to batch convert multiple URLs from the clipboard to MD files, so that I can download the articles that need to be downloaded in one place. I think this is a very practical feature

### ✔️ Solution

The plugin automatically recognizes multiple URLs of the clipboard and downloads them in bulk

**Comment by adamluckdev** [comment]
Thanks for the suggestion. It certainly points out workflow where user (like you) don't want to just save note but process multiple sources into one big note.

However I don't think your solution will satisfy broader audience of plugin, because there's necessity to format URLs to some pattern. I think creating new command to append content in currently open note will be better.

**Comment by indicatorvariable** [comment]
I agree with @lbgws2 for the feature request. 
To reiterate if the clipboard content contains a list of newline delimited set of URLs, the plugin can process each one individually and put them into separate markdown files. This would not require fundamentally changing the behaviour of the plugin. It is just overloading the parseClipboard function.

**Comment by adamluckdev** [comment]
Yeah, sorry I misread original post and thought @lbgws2 wants to create one big note.

In this case I agree with feature request and suggested format of URLs delimited by newline.

**Comment by lbgws2** [comment]
Perhaps this requirement can be listed as an experimental feature that can be enabled in the configuration



My habit is that when I have articles on the mobile that I need to read later, I automatically send them to an online document. Later, I can copy the URL list and focus on downloading them at a certain time

**Comment by jakonorce** [comment]
I also agree about this feature request - would really make this a power tool to convert lists of bookmarks.
